# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stpb.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stpb.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nstpb.proto\x12\x04stpb\"8\n\tStRequest\x12\x0e\n\x06\x63li_id\x18\x01 \x01(\x05\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65lete\x18\x03 \x01(\x08\"2\n\x04StKV\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0e\n\x06\x63li_id\x18\x03 \x01(\x05\"7\n\x07StEmpty\x12\r\n\x05\x65mpty\x18\x01 \x01(\t\x12\r\n\x05\x65rrno\x18\x03 \x01(\x08\x12\x0e\n\x06\x65rrmes\x18\x04 \x01(\t\":\n\nStResponse\x12\r\n\x05value\x18\x01 \x01(\t\x12\r\n\x05\x65rrno\x18\x03 \x01(\x08\x12\x0e\n\x06\x65rrmes\x18\x04 \x01(\t2\x91\x03\n\x12storagementService\x12,\n\x07getdata\x12\x0f.stpb.StRequest\x1a\x10.stpb.StResponse\x12$\n\x07putdata\x12\n.stpb.StKV\x1a\r.stpb.StEmpty\x12)\n\x07\x64\x65ldata\x12\x0f.stpb.StRequest\x1a\r.stpb.StEmpty\x12.\n\tmaGetdata\x12\x0f.stpb.StRequest\x1a\x10.stpb.StResponse\x12&\n\tmaPutdata\x12\n.stpb.StKV\x1a\r.stpb.StEmpty\x12+\n\tmaDeldata\x12\x0f.stpb.StRequest\x1a\r.stpb.StEmpty\x12\'\n\x05\x61\x62ort\x12\x0f.stpb.StRequest\x1a\r.stpb.StEmpty\x12(\n\x06\x63ommit\x12\x0f.stpb.StRequest\x1a\r.stpb.StEmpty\x12$\n\x04live\x12\r.stpb.StEmpty\x1a\r.stpb.StEmptyB\x11Z\x0f../storageprotob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stpb_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017../storageproto'
  _globals['_STREQUEST']._serialized_start=20
  _globals['_STREQUEST']._serialized_end=76
  _globals['_STKV']._serialized_start=78
  _globals['_STKV']._serialized_end=128
  _globals['_STEMPTY']._serialized_start=130
  _globals['_STEMPTY']._serialized_end=185
  _globals['_STRESPONSE']._serialized_start=187
  _globals['_STRESPONSE']._serialized_end=245
  _globals['_STORAGEMENTSERVICE']._serialized_start=248
  _globals['_STORAGEMENTSERVICE']._serialized_end=649
# @@protoc_insertion_point(module_scope)
