# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import stpb_pb2 as stpb__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in stpb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class storagementServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getdata = channel.unary_unary(
                '/stpb.storagementService/getdata',
                request_serializer=stpb__pb2.StRequest.SerializeToString,
                response_deserializer=stpb__pb2.StResponse.FromString,
                _registered_method=True)
        self.putdata = channel.unary_unary(
                '/stpb.storagementService/putdata',
                request_serializer=stpb__pb2.StKV.SerializeToString,
                response_deserializer=stpb__pb2.StEmpty.FromString,
                _registered_method=True)
        self.deldata = channel.unary_unary(
                '/stpb.storagementService/deldata',
                request_serializer=stpb__pb2.StRequest.SerializeToString,
                response_deserializer=stpb__pb2.StEmpty.FromString,
                _registered_method=True)
        self.maGetdata = channel.unary_unary(
                '/stpb.storagementService/maGetdata',
                request_serializer=stpb__pb2.StRequest.SerializeToString,
                response_deserializer=stpb__pb2.StResponse.FromString,
                _registered_method=True)
        self.maPutdata = channel.unary_unary(
                '/stpb.storagementService/maPutdata',
                request_serializer=stpb__pb2.StKV.SerializeToString,
                response_deserializer=stpb__pb2.StEmpty.FromString,
                _registered_method=True)
        self.maDeldata = channel.unary_unary(
                '/stpb.storagementService/maDeldata',
                request_serializer=stpb__pb2.StRequest.SerializeToString,
                response_deserializer=stpb__pb2.StEmpty.FromString,
                _registered_method=True)
        self.abort = channel.unary_unary(
                '/stpb.storagementService/abort',
                request_serializer=stpb__pb2.StRequest.SerializeToString,
                response_deserializer=stpb__pb2.StEmpty.FromString,
                _registered_method=True)
        self.commit = channel.unary_unary(
                '/stpb.storagementService/commit',
                request_serializer=stpb__pb2.StRequest.SerializeToString,
                response_deserializer=stpb__pb2.StEmpty.FromString,
                _registered_method=True)
        self.live = channel.unary_unary(
                '/stpb.storagementService/live',
                request_serializer=stpb__pb2.StEmpty.SerializeToString,
                response_deserializer=stpb__pb2.StEmpty.FromString,
                _registered_method=True)


class storagementServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getdata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def putdata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deldata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def maGetdata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def maPutdata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def maDeldata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def abort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def commit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def live(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_storagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getdata': grpc.unary_unary_rpc_method_handler(
                    servicer.getdata,
                    request_deserializer=stpb__pb2.StRequest.FromString,
                    response_serializer=stpb__pb2.StResponse.SerializeToString,
            ),
            'putdata': grpc.unary_unary_rpc_method_handler(
                    servicer.putdata,
                    request_deserializer=stpb__pb2.StKV.FromString,
                    response_serializer=stpb__pb2.StEmpty.SerializeToString,
            ),
            'deldata': grpc.unary_unary_rpc_method_handler(
                    servicer.deldata,
                    request_deserializer=stpb__pb2.StRequest.FromString,
                    response_serializer=stpb__pb2.StEmpty.SerializeToString,
            ),
            'maGetdata': grpc.unary_unary_rpc_method_handler(
                    servicer.maGetdata,
                    request_deserializer=stpb__pb2.StRequest.FromString,
                    response_serializer=stpb__pb2.StResponse.SerializeToString,
            ),
            'maPutdata': grpc.unary_unary_rpc_method_handler(
                    servicer.maPutdata,
                    request_deserializer=stpb__pb2.StKV.FromString,
                    response_serializer=stpb__pb2.StEmpty.SerializeToString,
            ),
            'maDeldata': grpc.unary_unary_rpc_method_handler(
                    servicer.maDeldata,
                    request_deserializer=stpb__pb2.StRequest.FromString,
                    response_serializer=stpb__pb2.StEmpty.SerializeToString,
            ),
            'abort': grpc.unary_unary_rpc_method_handler(
                    servicer.abort,
                    request_deserializer=stpb__pb2.StRequest.FromString,
                    response_serializer=stpb__pb2.StEmpty.SerializeToString,
            ),
            'commit': grpc.unary_unary_rpc_method_handler(
                    servicer.commit,
                    request_deserializer=stpb__pb2.StRequest.FromString,
                    response_serializer=stpb__pb2.StEmpty.SerializeToString,
            ),
            'live': grpc.unary_unary_rpc_method_handler(
                    servicer.live,
                    request_deserializer=stpb__pb2.StEmpty.FromString,
                    response_serializer=stpb__pb2.StEmpty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stpb.storagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stpb.storagementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class storagementService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getdata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stpb.storagementService/getdata',
            stpb__pb2.StRequest.SerializeToString,
            stpb__pb2.StResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def putdata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stpb.storagementService/putdata',
            stpb__pb2.StKV.SerializeToString,
            stpb__pb2.StEmpty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deldata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stpb.storagementService/deldata',
            stpb__pb2.StRequest.SerializeToString,
            stpb__pb2.StEmpty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def maGetdata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stpb.storagementService/maGetdata',
            stpb__pb2.StRequest.SerializeToString,
            stpb__pb2.StResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def maPutdata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stpb.storagementService/maPutdata',
            stpb__pb2.StKV.SerializeToString,
            stpb__pb2.StEmpty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def maDeldata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stpb.storagementService/maDeldata',
            stpb__pb2.StRequest.SerializeToString,
            stpb__pb2.StEmpty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def abort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stpb.storagementService/abort',
            stpb__pb2.StRequest.SerializeToString,
            stpb__pb2.StEmpty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stpb.storagementService/commit',
            stpb__pb2.StRequest.SerializeToString,
            stpb__pb2.StEmpty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def live(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stpb.storagementService/live',
            stpb__pb2.StEmpty.SerializeToString,
            stpb__pb2.StEmpty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
